[package]
name = "struct-update"
version = "0.2.0"
edition = "2021"
authors = ["MagicWenli <yxnian@outlook.com>"]
license = "MIT"

[lib]
path = "src/lib.rs"
proc-macro = true

[dependencies]
darling = "0.20.9"
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = "2.0.69"
